INFO: 2019-08-18 01:22:54,950: perform_upgrade() 'Last run version was 0.7.2 or earlier, current version is 0.7.2'
INFO: 2019-08-18 01:22:55,282: process_command() 'Received command: []'
INFO: 2019-08-18 01:22:55,288: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2019-08-18 01:22:55,318: load() 'Jumble loading'
INFO: 2019-08-18 01:22:55,320: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/__init__.py'
INFO: 2019-08-18 01:22:55,322: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/share/variety/plugins/quotes/GoodreadsSource.py'
INFO: 2019-08-18 01:22:55,343: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': '从 Goodreads.com 获取箴言', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-18 01:22:55,345: _walk_modules() 'Jumble loading module in QuotesDaddySource from /usr/share/variety/plugins/quotes/QuotesDaddySource.py'
INFO: 2019-08-18 01:22:55,348: load() 'Jumble found plugin class: <class 'QuotesDaddySource.QuotesDaddySource'>: {'name': 'QuotesDaddy', 'description': '从QuotesDaddy的每日箴言RSS订阅中中获取箴言。不支持按标签或作者搜索。', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-18 01:22:55,348: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/quotes/__init__.py'
INFO: 2019-08-18 01:22:55,350: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/share/variety/plugins/quotes/LocalFilesSource.py'
INFO: 2019-08-18 01:22:55,352: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-18 01:22:55,353: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/share/variety/plugins/quotes/QuotationsPageSource.py'
INFO: 2019-08-18 01:22:55,356: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': '从 QuotationsPage.com 获取箴言', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-18 01:22:55,363: reload_config() 'Creating new downloader for type 6, location Random wallpapers from Desktoppr.co'
INFO: 2019-08-18 01:22:55,363: reload_config() 'Creating new downloader for type 15, location Bing Photo of the Day'
INFO: 2019-08-18 01:22:55,364: reload_config() 'Creating new downloader for type 16, location High-resolution photos from Unsplash.com'
INFO: 2019-08-18 01:22:55,364: reload_config() 'Creating new downloader for type 8, location NASA's Astronomy Picture of the Day'
INFO: 2019-08-18 01:22:55,364: reload_config() 'Creating new downloader for type 7, location user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2019-08-18 01:22:55,364: log_options() 'Loaded options:'
INFO: 2019-08-18 01:22:55,365: log_options() 'change_enabled = True'
INFO: 2019-08-18 01:22:55,365: log_options() 'change_interval = 30'
INFO: 2019-08-18 01:22:55,365: log_options() 'change_on_start = False'
INFO: 2019-08-18 01:22:55,365: log_options() 'clipboard_enabled = False'
INFO: 2019-08-18 01:22:55,365: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2019-08-18 01:22:55,365: log_options() 'clipboard_use_whitelist = True'
INFO: 2019-08-18 01:22:55,365: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2019-08-18 01:22:55,365: log_options() 'clock_enabled = False'
INFO: 2019-08-18 01:22:55,365: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2019-08-18 01:22:55,365: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2019-08-18 01:22:55,365: log_options() 'configfile = /home/breathiness/.config/variety/variety.conf'
INFO: 2019-08-18 01:22:55,365: log_options() 'copyto_enabled = False'
INFO: 2019-08-18 01:22:55,365: log_options() 'copyto_folder = Default'
INFO: 2019-08-18 01:22:55,366: log_options() 'desired_color = [160, 160, 160]'
INFO: 2019-08-18 01:22:55,366: log_options() 'desired_color_enabled = False'
INFO: 2019-08-18 01:22:55,366: log_options() 'download_enabled = True'
INFO: 2019-08-18 01:22:55,366: log_options() 'download_folder = /home/breathiness/.config/variety/Downloaded'
INFO: 2019-08-18 01:22:55,366: log_options() 'download_interval = 600'
INFO: 2019-08-18 01:22:55,366: log_options() 'favorites_folder = /home/breathiness/.config/variety/Favorites'
INFO: 2019-08-18 01:22:55,366: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2019-08-18 01:22:55,366: log_options() 'fetched_folder = /home/breathiness/.config/variety/Fetched'
INFO: 2019-08-18 01:22:55,366: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2019-08-18 01:22:55,366: log_options() 'icon = Light'
INFO: 2019-08-18 01:22:55,366: log_options() 'lightness_enabled = False'
INFO: 2019-08-18 01:22:55,366: log_options() 'lightness_mode = 0'
INFO: 2019-08-18 01:22:55,366: log_options() 'min_rating = 4'
INFO: 2019-08-18 01:22:55,366: log_options() 'min_rating_enabled = False'
INFO: 2019-08-18 01:22:55,366: log_options() 'min_size = 80'
INFO: 2019-08-18 01:22:55,366: log_options() 'min_size_enabled = False'
INFO: 2019-08-18 01:22:55,366: log_options() 'quota_enabled = True'
INFO: 2019-08-18 01:22:55,367: log_options() 'quota_size = 500'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_authors = '
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_bg_opacity = 55'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_change_enabled = False'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_change_interval = 300'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_disabled_sources = ['QuotesDaddy']'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_enabled = False'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_favorites_file = /home/breathiness/.config/variety/favorite_quotes.txt'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_hpos = 100'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_tags = '
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_text_shadow = False'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_vpos = 40'
INFO: 2019-08-18 01:22:55,367: log_options() 'quotes_width = 70'
INFO: 2019-08-18 01:22:55,367: log_options() 'safe_mode = False'
INFO: 2019-08-18 01:22:55,367: log_options() 'slideshow_custom_enabled = False'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_custom_folder = /home/breathiness/图片'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_downloads_enabled = False'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_fade = 0.4'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_favorites_enabled = True'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_mode = Fullscreen'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_monitor = All'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_pan = 0.05'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_seconds = 6.0'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_sort_order = Random'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_sources_enabled = True'
INFO: 2019-08-18 01:22:55,368: log_options() 'slideshow_zoom = 0.2'
INFO: 2019-08-18 01:22:55,368: log_options() 'smart_enabled = False'
INFO: 2019-08-18 01:22:55,368: log_options() 'smart_notice_shown = False'
INFO: 2019-08-18 01:22:55,368: log_options() 'smart_register_shown = False'
INFO: 2019-08-18 01:22:55,368: log_options() 'sources = [[True, 3, 'The Favorites folder'], [True, 4, 'The Fetched folder'], [True, 2, '/usr/share/backgrounds'], [True, 6, 'Random wallpapers from Desktoppr.co'], [True, 15, 'Bing Photo of the Day'], [True, 16, 'High-resolution photos from Unsplash.com'], [True, 8, "NASA's Astronomy Picture of the Day"], [False, 11, 'World Sunlight Map - live wallpaper from Die.net'], [True, 7, 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;']]'
INFO: 2019-08-18 01:22:55,368: log_options() 'stats_enabled = True'
INFO: 2019-08-18 01:22:55,368: log_options() 'stats_notice_shown = False'
INFO: 2019-08-18 01:22:55,369: log_options() 'sync_enabled = True'
INFO: 2019-08-18 01:22:55,369: log_options() 'use_landscape_enabled = True'
INFO: 2019-08-18 01:22:55,369: reload_config() 'No need to clear prepared queue'
INFO: 2019-08-18 01:22:55,369: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 30'
INFO: 2019-08-18 01:22:55,369: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:22:55,377: regular_change_thread() 'regular_change thread running'
INFO: 2019-08-18 01:22:55,377: prepare_thread() 'Prepare thread running'
INFO: 2019-08-18 01:22:55,377: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2019-08-18 01:22:55,378: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:22:55,383: update_indicator_icon() 'Creating indicator'
WARNING: 2019-08-18 01:22:55,461: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2019-08-18 01:22:55,464: create_indicator() 'indicator backend: fallback tray'
INFO: 2019-08-18 01:22:55,480: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized4_16x9.jpg, time: 1566062575.4803195'
INFO: 2019-08-18 01:22:55,500: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:22:55,542: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:22:55,633: set_from_theme_icon() 'Showing status icon variety-indicator from GTK theme'
INFO: 2019-08-18 01:22:55,644: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:22:57,330: reload() 'Reloading preferences dialog'
INFO: 2019-08-18 01:23:15,399: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
INFO: 2019-08-18 01:23:25,370: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:23:25,370: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_default_background.jpg'
INFO: 2019-08-18 01:23:25,370: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:23:25,371: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_default_background.jpg, time: 1566062605.3712122'
INFO: 2019-08-18 01:23:25,401: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_default_background.jpg'
ERROR: 2019-08-18 01:23:26,270: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fa903ed4e90>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903ed4e90>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903ed4e90>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-18 01:23:55,776: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:23:55,777: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:23:55,777: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:23:55,778: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/deserted.jpg, time: 1566062635.7784085'
INFO: 2019-08-18 01:23:55,806: update_indicator() 'Setting file info to: /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:23:56,293: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-18 01:24:04,366: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fa903f10250>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903f10250>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903f10250>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-18 01:24:26,197: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:24:26,198: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:24:26,198: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 01:24:26,198: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566062666.1987507'
INFO: 2019-08-18 01:24:26,236: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:24:34,384: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-18 01:24:49,408: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fa903f0b3d0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903f0b3d0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903f0b3d0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-18 01:24:56,617: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:24:56,617: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:24:56,617: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 01:24:56,618: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/breath_i3.jpg, time: 1566062696.6184366'
INFO: 2019-08-18 01:24:56,648: update_indicator() 'Setting file info to: /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:25:19,433: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
INFO: 2019-08-18 01:25:27,383: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:25:27,384: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:25:27,384: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 01:25:27,384: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566062727.384727'
INFO: 2019-08-18 01:25:27,415: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
ERROR: 2019-08-18 01:25:27,515: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fa903ed9c50>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903ed9c50>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa903ed9c50>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-18 01:25:57,533: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
INFO: 2019-08-18 01:25:57,888: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:25:57,888: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:25:57,889: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 01:25:57,889: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser_manjaro-i3.jpg, time: 1566062757.8895369'
INFO: 2019-08-18 01:25:57,919: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser_manjaro-i3.jpg'
ERROR: 2019-08-18 01:26:07,551: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fa924440910>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa924440910>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa924440910>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-18 01:26:28,295: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:26:28,295: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:26:28,296: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 01:26:28,296: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/blackcat.jpg, time: 1566062788.29627'
INFO: 2019-08-18 01:26:28,328: update_indicator() 'Setting file info to: /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:26:58,731: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:26:58,731: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:26:58,732: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 01:26:58,732: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized3_16x9.jpg, time: 1566062818.7324595'
INFO: 2019-08-18 01:26:58,756: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:27:29,264: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:27:29,265: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:27:29,265: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 01:27:29,265: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized4_16x9.jpg, time: 1566062849.2657974'
INFO: 2019-08-18 01:27:29,296: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:27:59,805: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:27:59,806: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:27:59,806: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 01:27:59,806: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bluemountain.jpg, time: 1566062879.806756'
INFO: 2019-08-18 01:27:59,830: update_indicator() 'Setting file info to: /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:28:30,207: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:28:30,208: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:28:30,208: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 01:28:30,208: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566062910.2087266'
INFO: 2019-08-18 01:28:30,243: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:29:00,630: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:29:00,631: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 01:29:00,631: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 01:29:00,632: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/maia_i3.jpg, time: 1566062940.632022'
INFO: 2019-08-18 01:29:00,675: update_indicator() 'Setting file info to: /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 01:29:31,403: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:29:31,404: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:29:31,404: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 01:29:31,404: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/adapta_i3.jpg, time: 1566062971.404771'
INFO: 2019-08-18 01:29:31,435: update_indicator() 'Setting file info to: /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:30:02,135: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:30:02,136: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 01:30:02,136: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 01:30:02,136: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:30:02,143: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/glowing_lake.jpg, time: 1566063002.1435533'
INFO: 2019-08-18 01:30:02,160: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:30:02,183: update_indicator() 'Setting file info to: /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 01:30:32,550: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:30:32,551: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:30:32,551: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:30:32,552: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized3_16x9.jpg, time: 1566063032.5520642'
INFO: 2019-08-18 01:30:32,590: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:31:03,106: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:31:03,107: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:31:03,107: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:31:03,108: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/breath_i3.jpg, time: 1566063063.1083722'
INFO: 2019-08-18 01:31:03,140: update_indicator() 'Setting file info to: /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:31:33,900: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:31:33,901: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:31:33,901: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 01:31:33,902: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/blackcat.jpg, time: 1566063093.9020376'
INFO: 2019-08-18 01:31:33,941: update_indicator() 'Setting file info to: /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:32:04,330: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:32:04,331: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/watercolor-grunge.jpg'
INFO: 2019-08-18 01:32:04,331: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 01:32:04,332: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/watercolor-grunge.jpg, time: 1566063124.332059'
INFO: 2019-08-18 01:32:04,363: update_indicator() 'Setting file info to: /usr/share/backgrounds/watercolor-grunge.jpg'
INFO: 2019-08-18 01:32:34,714: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:32:34,715: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized2_16x9.jpg'
INFO: 2019-08-18 01:32:34,715: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 01:32:34,716: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized2_16x9.jpg, time: 1566063154.7161462'
INFO: 2019-08-18 01:32:34,801: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized2_16x9.jpg'
INFO: 2019-08-18 01:32:55,384: purge_downloaded() 'Refreshed download folder size: 0 mb'
INFO: 2019-08-18 01:32:55,385: download_one() 'Downloading a random image from desktoppr.co'
ERROR: 2019-08-18 01:33:04,338: request() 'SSL Error for url https://api.desktoppr.co/1/wallpapers/random:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
ERROR: 2019-08-18 01:33:04,341: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 986, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1018, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.7/site-packages/variety/DesktopprDownloader.py", line 35, in download_one
    response = Util.fetch_json(self.location)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
INFO: 2019-08-18 01:33:05,932: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:33:05,932: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:33:05,933: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 01:33:05,933: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566063185.9335647'
INFO: 2019-08-18 01:33:05,964: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:33:36,349: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:33:36,350: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:33:36,350: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 01:33:36,350: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/adapta_i3.jpg, time: 1566063216.3509803'
INFO: 2019-08-18 01:33:36,381: update_indicator() 'Setting file info to: /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:34:07,095: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:34:07,095: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 01:34:07,095: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 01:34:07,096: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/maia_i3.jpg, time: 1566063247.0964224'
INFO: 2019-08-18 01:34:07,127: update_indicator() 'Setting file info to: /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 01:34:37,883: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:34:37,883: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:34:37,884: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 01:34:37,884: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566063277.8844247'
INFO: 2019-08-18 01:34:37,915: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:35:08,305: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:35:08,306: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:35:08,306: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 01:35:08,307: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566063308.307287'
INFO: 2019-08-18 01:35:08,338: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:35:38,742: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:35:38,743: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:35:38,744: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 01:35:38,744: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/layers-blue-lockscreen.jpg, time: 1566063338.7442834'
INFO: 2019-08-18 01:35:38,791: update_indicator() 'Setting file info to: /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:36:09,194: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:36:09,195: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:36:09,195: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 01:36:09,196: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/deserted.jpg, time: 1566063369.1960242'
INFO: 2019-08-18 01:36:09,232: update_indicator() 'Setting file info to: /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:36:39,646: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:36:39,647: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:36:39,647: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 01:36:39,648: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_solarized.jpg, time: 1566063399.6481884'
INFO: 2019-08-18 01:36:39,707: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:37:10,106: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:37:10,107: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:37:10,107: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 01:37:10,107: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:37:10,114: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566063430.1141477'
INFO: 2019-08-18 01:37:10,129: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:37:10,149: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:37:40,624: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:37:40,624: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:37:40,625: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:37:40,625: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/deserted.jpg, time: 1566063460.6254444'
INFO: 2019-08-18 01:37:40,654: update_indicator() 'Setting file info to: /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 01:38:11,087: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:38:11,088: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/watercolor-grunge.jpg'
INFO: 2019-08-18 01:38:11,088: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:38:11,088: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/watercolor-grunge.jpg, time: 1566063491.0887775'
INFO: 2019-08-18 01:38:11,120: update_indicator() 'Setting file info to: /usr/share/backgrounds/watercolor-grunge.jpg'
INFO: 2019-08-18 01:38:41,426: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:38:41,427: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:38:41,427: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 01:38:41,427: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/paper.jpg, time: 1566063521.4278965'
INFO: 2019-08-18 01:38:41,459: update_indicator() 'Setting file info to: /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:39:11,908: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:39:11,909: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized2_16x9.jpg'
INFO: 2019-08-18 01:39:11,909: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 01:39:11,909: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized2_16x9.jpg, time: 1566063551.909809'
INFO: 2019-08-18 01:39:11,940: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized2_16x9.jpg'
INFO: 2019-08-18 01:39:42,444: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:39:42,445: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:39:42,445: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 01:39:42,446: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bluemountain.jpg, time: 1566063582.4461057'
INFO: 2019-08-18 01:39:42,476: update_indicator() 'Setting file info to: /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:40:12,921: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:40:12,921: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:40:12,922: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 01:40:12,922: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566063612.9226089'
INFO: 2019-08-18 01:40:12,946: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:40:43,497: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:40:43,498: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 01:40:43,498: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 01:40:43,499: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser-i3-2.jpg, time: 1566063643.499324'
INFO: 2019-08-18 01:40:43,529: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 01:41:13,985: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:41:13,986: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:41:13,986: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 01:41:13,987: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566063673.9872901'
INFO: 2019-08-18 01:41:14,015: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:41:44,473: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:41:44,473: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:41:44,474: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 01:41:44,474: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/breath_i3.jpg, time: 1566063704.474729'
INFO: 2019-08-18 01:41:44,504: update_indicator() 'Setting file info to: /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:42:15,244: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:42:15,245: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:42:15,245: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 01:42:15,246: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/layers-blue-lockscreen.jpg, time: 1566063735.2460299'
INFO: 2019-08-18 01:42:15,274: update_indicator() 'Setting file info to: /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:42:45,665: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:42:45,666: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:42:45,666: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 01:42:45,667: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566063765.6672344'
INFO: 2019-08-18 01:42:45,696: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:42:55,379: download_one() 'Downloading a random image from desktoppr.co'
ERROR: 2019-08-18 01:43:07,886: request() 'SSL Error for url https://api.desktoppr.co/1/wallpapers/random:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
ERROR: 2019-08-18 01:43:07,887: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 986, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1018, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.7/site-packages/variety/DesktopprDownloader.py", line 35, in download_one
    response = Util.fetch_json(self.location)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
INFO: 2019-08-18 01:43:16,077: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:43:16,077: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:43:16,078: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 01:43:16,078: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser_manjaro-i3.jpg, time: 1566063796.0786893'
INFO: 2019-08-18 01:43:16,108: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:43:46,442: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:43:46,443: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:43:46,443: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 01:43:46,444: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566063826.4443314'
INFO: 2019-08-18 01:43:46,474: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:44:16,872: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:44:16,873: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:44:16,873: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 01:44:16,874: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:44:16,880: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized1_16x9.jpg, time: 1566063856.8809588'
INFO: 2019-08-18 01:44:16,896: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:44:16,935: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:44:47,797: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:44:47,797: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:44:47,798: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:44:47,798: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566063887.798408'
INFO: 2019-08-18 01:44:47,822: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:45:18,276: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:45:18,276: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:45:18,277: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:45:18,277: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized1_16x9.jpg, time: 1566063918.2777588'
INFO: 2019-08-18 01:45:18,303: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:45:49,100: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:45:49,100: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:45:49,100: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 01:45:49,102: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/paper.jpg, time: 1566063949.1021876'
INFO: 2019-08-18 01:45:49,157: update_indicator() 'Setting file info to: /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:46:19,990: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:46:19,991: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:46:19,992: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 01:46:19,992: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566063979.992601'
INFO: 2019-08-18 01:46:20,072: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:46:51,174: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:46:51,175: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:46:51,175: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 01:46:51,176: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized3_16x9.jpg, time: 1566064011.1760705'
INFO: 2019-08-18 01:46:51,243: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:47:22,149: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:47:22,150: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:47:22,150: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 01:47:22,151: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566064042.1511338'
INFO: 2019-08-18 01:47:22,178: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:47:52,622: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:47:52,623: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 01:47:52,624: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 01:47:52,625: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/glowing_lake.jpg, time: 1566064072.6255772'
INFO: 2019-08-18 01:47:52,658: update_indicator() 'Setting file info to: /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 01:48:23,095: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:48:23,095: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_default_background.jpg'
INFO: 2019-08-18 01:48:23,095: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 01:48:23,096: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_default_background.jpg, time: 1566064103.0965006'
INFO: 2019-08-18 01:48:23,128: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_default_background.jpg'
INFO: 2019-08-18 01:48:53,564: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:48:53,565: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:48:53,565: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 01:48:53,566: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_solarized.jpg, time: 1566064133.5661294'
INFO: 2019-08-18 01:48:53,598: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:49:24,018: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:49:24,018: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/RREDesigns_i3.jpg'
INFO: 2019-08-18 01:49:24,019: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 01:49:24,019: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/RREDesigns_i3.jpg, time: 1566064164.0195272'
INFO: 2019-08-18 01:49:24,047: update_indicator() 'Setting file info to: /usr/share/backgrounds/RREDesigns_i3.jpg'
INFO: 2019-08-18 01:49:54,391: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:49:54,392: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:49:54,392: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 01:49:54,393: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566064194.3933935'
INFO: 2019-08-18 01:49:54,425: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:50:24,882: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:50:24,883: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:50:24,883: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 01:50:24,883: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bluemountain.jpg, time: 1566064224.8839474'
INFO: 2019-08-18 01:50:24,933: update_indicator() 'Setting file info to: /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:50:55,345: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:50:55,346: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:50:55,347: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 01:50:55,347: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser_manjaro-i3.jpg, time: 1566064255.3479795'
INFO: 2019-08-18 01:50:55,436: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:51:26,341: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:51:26,342: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:51:26,343: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 01:51:26,343: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:51:26,352: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/breath_i3.jpg, time: 1566064286.3529823'
INFO: 2019-08-18 01:51:26,375: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:51:26,431: update_indicator() 'Setting file info to: /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:51:58,159: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:51:58,160: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:51:58,161: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:51:58,162: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/adapta_i3.jpg, time: 1566064318.1622365'
INFO: 2019-08-18 01:51:58,273: update_indicator() 'Setting file info to: /usr/share/backgrounds/adapta_i3.jpg'
INFO: 2019-08-18 01:52:30,619: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:52:30,620: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:52:30,620: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:52:30,621: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566064350.6211808'
INFO: 2019-08-18 01:52:30,654: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 01:52:55,379: parse_server_options() 'Flickr: parsing serverside options'
ERROR: 2019-08-18 01:52:55,381: parse_server_options() 'Could not parse Flickr serverside options, using defaults 60, 600'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/Downloader.py", line 143, in parse_server_options
    options = self.parent.server_options[key]
KeyError: 'flickr'
INFO: 2019-08-18 01:52:55,382: download_one() 'Downloading an image from Flickr, user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2019-08-18 01:52:55,382: download_one() 'Queue size: 0'
INFO: 2019-08-18 01:52:55,382: fill_queue() 'Filling Flickr download queue: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2019-08-18 01:52:55,382: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00'
INFO: 2019-08-18 01:53:01,112: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:53:01,112: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/breath_i3.jpg'
INFO: 2019-08-18 01:53:01,112: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 01:53:01,113: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/breath_i3.jpg, time: 1566064381.1131744'
INFO: 2019-08-18 01:53:01,136: update_indicator() 'Setting file info to: /usr/share/backgrounds/breath_i3.jpg'
ERROR: 2019-08-18 01:53:01,181: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] 网络不可达

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa903f08810>: Failed to establish a new connection: [Errno 101] 网络不可达

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa903f08810>: Failed to establish a new connection: [Errno 101] 网络不可达'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 986, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1018, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.7/site-packages/variety/FlickrDownloader.py", line 142, in download_one
    self.fill_queue()
  File "/usr/lib/python3.7/site-packages/variety/FlickrDownloader.py", line 165, in fill_queue
    resp = FlickrDownloader.fetch(call)
  File "/usr/lib/python3.7/site-packages/variety/FlickrDownloader.py", line 60, in fetch
    return Util.fetch_json(call)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa903f08810>: Failed to establish a new connection: [Errno 101] 网络不可达'))
INFO: 2019-08-18 01:53:31,859: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:53:31,859: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 01:53:31,860: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 01:53:31,860: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser-i3-2.jpg, time: 1566064411.8605812'
INFO: 2019-08-18 01:53:31,891: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 01:54:02,344: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:54:02,345: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:54:02,345: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 01:54:02,346: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_solarized.jpg, time: 1566064442.3463125'
INFO: 2019-08-18 01:54:02,387: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_solarized.jpg'
INFO: 2019-08-18 01:54:32,810: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:54:32,811: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:54:32,812: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 01:54:32,812: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized4_16x9.jpg, time: 1566064472.8123622'
INFO: 2019-08-18 01:54:32,846: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 01:55:03,452: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:55:03,453: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:55:03,454: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 01:55:03,454: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/layers-blue-lockscreen.jpg, time: 1566064503.454475'
INFO: 2019-08-18 01:55:03,600: update_indicator() 'Setting file info to: /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 01:55:34,445: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:55:34,446: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:55:34,446: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 01:55:34,446: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/blackcat.jpg, time: 1566064534.446948'
INFO: 2019-08-18 01:55:34,483: update_indicator() 'Setting file info to: /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 01:56:05,989: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:56:05,990: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:56:05,990: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 01:56:05,992: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566064565.992764'
INFO: 2019-08-18 01:56:06,162: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 01:56:39,278: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:56:39,278: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:56:39,281: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 01:56:39,283: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/paper.jpg, time: 1566064599.2834845'
INFO: 2019-08-18 01:56:39,403: update_indicator() 'Setting file info to: /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 01:57:11,058: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:57:11,058: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:57:11,059: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 01:57:11,059: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566064631.059664'
INFO: 2019-08-18 01:57:11,110: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 01:57:41,755: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:57:41,756: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:57:41,757: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 01:57:41,757: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized3_16x9.jpg, time: 1566064661.7578454'
INFO: 2019-08-18 01:57:41,844: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized3_16x9.jpg'
INFO: 2019-08-18 01:58:13,125: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:58:13,126: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:58:13,127: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 01:58:13,128: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566064693.1284912'
INFO: 2019-08-18 01:58:13,204: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 01:58:44,306: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:58:44,307: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:58:44,307: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 01:58:44,307: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 01:58:44,317: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized1_16x9.jpg, time: 1566064724.3172193'
INFO: 2019-08-18 01:58:44,332: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 01:58:44,366: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized1_16x9.jpg'
INFO: 2019-08-18 01:59:15,210: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:59:15,211: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:59:15,211: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 01:59:15,222: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bluemountain.jpg, time: 1566064755.222474'
INFO: 2019-08-18 01:59:15,295: update_indicator() 'Setting file info to: /usr/share/backgrounds/bluemountain.jpg'
INFO: 2019-08-18 01:59:47,183: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 01:59:47,184: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 01:59:47,184: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 01:59:47,185: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser_manjaro-i3.jpg, time: 1566064787.184986'
INFO: 2019-08-18 01:59:47,241: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser_manjaro-i3.jpg'
INFO: 2019-08-18 02:00:17,603: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:00:17,604: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 02:00:17,604: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 02:00:17,605: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/muser-i3-2.jpg, time: 1566064817.605299'
INFO: 2019-08-18 02:00:17,636: update_indicator() 'Setting file info to: /usr/share/backgrounds/muser-i3-2.jpg'
INFO: 2019-08-18 02:00:48,195: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:00:48,196: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 02:00:48,196: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 02:00:48,196: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/deserted.jpg, time: 1566064848.1968102'
INFO: 2019-08-18 02:00:48,275: update_indicator() 'Setting file info to: /usr/share/backgrounds/deserted.jpg'
INFO: 2019-08-18 02:01:19,093: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:01:19,094: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 02:01:19,094: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 02:01:19,094: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/bentwood.jpg, time: 1566064879.0946875'
INFO: 2019-08-18 02:01:19,120: update_indicator() 'Setting file info to: /usr/share/backgrounds/bentwood.jpg'
INFO: 2019-08-18 02:01:49,525: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:01:49,526: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 02:01:49,526: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 02:01:49,527: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566064909.5274553'
INFO: 2019-08-18 02:01:49,558: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 02:02:20,000: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:02:20,001: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 02:02:20,001: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2019-08-18 02:02:20,002: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/paper.jpg, time: 1566064940.0019896'
INFO: 2019-08-18 02:02:20,064: update_indicator() 'Setting file info to: /usr/share/backgrounds/paper.jpg'
INFO: 2019-08-18 02:02:51,082: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:02:51,083: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 02:02:51,083: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2019-08-18 02:02:51,083: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/glowing_lake.jpg, time: 1566064971.0838778'
INFO: 2019-08-18 02:02:51,116: update_indicator() 'Setting file info to: /usr/share/backgrounds/glowing_lake.jpg'
INFO: 2019-08-18 02:02:55,380: download_one() 'Downloading a random image from desktoppr.co'
ERROR: 2019-08-18 02:02:58,814: request() 'SSL Error for url https://api.desktoppr.co/1/wallpapers/random:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
ERROR: 2019-08-18 02:02:58,816: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 986, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1018, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.7/site-packages/variety/DesktopprDownloader.py", line 35, in download_one
    response = Util.fetch_json(self.location)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.desktoppr.co', port=443): Max retries exceeded with url: /1/wallpapers/random (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
INFO: 2019-08-18 02:03:21,500: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:03:21,500: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 02:03:21,500: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2019-08-18 02:03:21,501: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/maia_i3.jpg, time: 1566065001.5013657'
INFO: 2019-08-18 02:03:21,531: update_indicator() 'Setting file info to: /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 02:03:52,393: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:03:52,393: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 02:03:52,394: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2019-08-18 02:03:52,394: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/ant_mi3.jpg, time: 1566065032.3944418'
INFO: 2019-08-18 02:03:52,425: update_indicator() 'Setting file info to: /usr/share/backgrounds/ant_mi3.jpg'
INFO: 2019-08-18 02:04:22,929: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:04:22,930: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 02:04:22,930: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2019-08-18 02:04:22,930: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/layers-blue-lockscreen.jpg, time: 1566065062.93097'
INFO: 2019-08-18 02:04:22,962: update_indicator() 'Setting file info to: /usr/share/backgrounds/layers-blue-lockscreen.jpg'
INFO: 2019-08-18 02:04:53,441: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:04:53,442: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/i3_default_background.jpg'
INFO: 2019-08-18 02:04:53,442: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2019-08-18 02:04:53,443: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/i3_default_background.jpg, time: 1566065093.4430826'
INFO: 2019-08-18 02:04:53,473: update_indicator() 'Setting file info to: /usr/share/backgrounds/i3_default_background.jpg'
INFO: 2019-08-18 02:05:23,872: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:05:23,872: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/manjaro-i3-illyria.png'
INFO: 2019-08-18 02:05:23,872: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2019-08-18 02:05:23,873: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/manjaro-i3-illyria.png, time: 1566065123.8736145'
INFO: 2019-08-18 02:05:23,943: update_indicator() 'Setting file info to: /usr/share/backgrounds/manjaro-i3-illyria.png'
INFO: 2019-08-18 02:05:54,713: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:05:54,714: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 02:05:54,714: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2019-08-18 02:05:54,714: prepare_thread() 'Preparing some images'
INFO: 2019-08-18 02:05:54,721: prepare_thread() 'After search prepared buffer contains 24 images'
INFO: 2019-08-18 02:05:54,721: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized4_16x9.jpg, time: 1566065154.7212837'
INFO: 2019-08-18 02:05:54,745: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 02:06:25,375: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:06:25,376: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 02:06:25,376: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2019-08-18 02:06:25,377: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/blackcat.jpg, time: 1566065185.377328'
INFO: 2019-08-18 02:06:25,408: update_indicator() 'Setting file info to: /usr/share/backgrounds/blackcat.jpg'
INFO: 2019-08-18 02:06:55,864: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:06:55,864: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 02:06:55,864: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2019-08-18 02:06:55,865: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/mi3_solarized4_16x9.jpg, time: 1566065215.8655193'
INFO: 2019-08-18 02:06:55,899: update_indicator() 'Setting file info to: /usr/share/backgrounds/mi3_solarized4_16x9.jpg'
INFO: 2019-08-18 02:07:26,460: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:07:26,461: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 02:07:26,461: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2019-08-18 02:07:26,462: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/woven.jpg, time: 1566065246.4623923'
INFO: 2019-08-18 02:07:26,497: update_indicator() 'Setting file info to: /usr/share/backgrounds/woven.jpg'
INFO: 2019-08-18 02:07:56,985: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:07:56,986: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 02:07:56,986: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2019-08-18 02:07:56,987: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/future2.jpg, time: 1566065276.9870672'
INFO: 2019-08-18 02:07:57,028: update_indicator() 'Setting file info to: /usr/share/backgrounds/future2.jpg'
INFO: 2019-08-18 02:08:27,503: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:08:27,504: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/RREDesigns_i3.jpg'
INFO: 2019-08-18 02:08:27,504: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2019-08-18 02:08:27,505: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/RREDesigns_i3.jpg, time: 1566065307.50516'
INFO: 2019-08-18 02:08:27,536: update_indicator() 'Setting file info to: /usr/share/backgrounds/RREDesigns_i3.jpg'
INFO: 2019-08-18 02:08:57,942: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-08-18 02:08:57,942: set_wallpaper() 'Calling set_wallpaper with /usr/share/backgrounds/maia_i3.jpg'
INFO: 2019-08-18 02:08:57,942: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2019-08-18 02:08:57,943: do_set_wp() 'Calling do_set_wp with /usr/share/backgrounds/maia_i3.jpg, time: 1566065337.943583'
INFO: 2019-08-18 02:08:57,974: update_indicator() 'Setting file info to: /usr/share/backgrounds/maia_i3.jpg'
